services:
  fake_youtube:
    build: ./services/fake_youtube
    env_file:
      - .env.docker
    ports:
      - "8001:8000"
    command: python -u -m uvicorn app:app --host 0.0.0.0 --port 8000

  fake_instagram:
    build: ./services/fake_instagram
    env_file:
      - .env.docker
    ports:
      - "8002:8000"
    command: python -u -m uvicorn app:app --host 0.0.0.0 --port 8000

  scheduler:
    build: ./services/scheduler
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - fake_youtube
      - fake_instagram
    command: python -u -m uvicorn scheduler:app --host 0.0.0.0 --port 8000 

  worker:
    build: ./services/worker
    env_file:
      - .env.docker
    depends_on:
      - scheduler
      - fake_youtube
      - fake_instagram
      - monitoring
    command: python -u worker.py

  monitoring:
    build: ./services/monitoring
    ports:
      - "8003:8000"
    env_file:
      - .env.docker