server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/scheduler/ {
        proxy_pass http://scheduler:8000/;
    }

    location /api/youtube/ {
        proxy_pass http://mock_youtube:8000/;
    }

    location /api/instagram/ {
        proxy_pass http://mock_instagram:8000/;
    }

    location /api/monitoring/ {
        proxy_pass http://monitoring:8000/;
    }
}
